//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_H
#define METASPRITE_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_TILE_ORIGIN 0
#define font_TILE_W 8
#define font_TILE_H 8
#define font_WIDTH 128
#define font_HEIGHT 64
#define font_TILE_COUNT 128

BANKREF_EXTERN(font)

extern const uint8_t font_tiles[2048];

#endif
